### ISSUE TITLE
Colour-code weblit tags

### ISSUE THREAD

**Issue by dajbelshaw** [toolness/weblitmapper#10]
Not at all urgent, but it would be awesome if all of the competencies under each strand had the relevant background colour. This would help quick recognition / mental filing.

e.g. 'Search' competency would have a background colour of red as it is under the 'Exploring strand.

Colours on WebLitMap image here: https://wiki.mozilla.org/Webmaker/WebLiteracyMap

**Comment by toolness** [comment]
Done in f879ce8647661476bd03e4af16a27ccf04631342!
