### ISSUE TITLE
Make it easy to see all resources with a given weblit tag

### ISSUE THREAD

**Issue by toolness** [toolness/weblitmapper#9]
Ideally the user should be able to click somewhere on the weblit grid and see all the resources tagged with it.

**Comment by dajbelshaw** [comment]
Agreed. A good place for this would be at the top of the 'browse' page. If they were all ticked/selected by default, you could untick/unselect to narrow down.

**Comment by dajbelshaw** [comment]
Another, potentially more interesting way of doing it would be to have a _random_ ticking/selection of boxes which would then highlight different resources on page refresh. The user would still be able to select those that she is looking for.

**Comment by toolness** [comment]
Ok, I've added a very basic Google-esque "command line" filter in d431e68ae4b64598fb1ae9801b9feb0bd8cd938b. I figure I can layer a more friendly GUI on top of it later, just as Google does, e,g. where your checkbox ticks are dynamically converted into their command-line equivalents and vice versa.

Given the relatively advanced web literacy of our mentor community, I'm hoping this is a reasonable strategy, since implementing the command-line filter is a lot faster than implementing and styling a form-based interface. (It's also more powerful, given literate-enough users.)

I also added somewhat extensive help for the filter criteria syntax in 385fdf8bb11a9190af230aa4cc55e032ad2c18df, which is viewable by clicking on a "help" button.

You can see the changes live now at http://weblitmapper.webmakerprototypes.org/!
